site_name: PRESS Methodology Note
site_url: https://paris21-data.github.io/PRESS/
docs_dir: docs
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: deep orange
    
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: deep orange
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PARIS21-DATA


# Optional: Plugins to enhance functionality
plugins:
  - search
  - mkdocstrings
  - autorefs:
      link_titles: false

# Navigation (sidebar) structure
nav:
  - Home: index.md
  - 1 Introduction: 01_introduction.md
  - 2 Data Sources: 02_data_sources.md
  - Code: 
      src:
        - download crs: src/download_crs.md
        - text processing: src/text_processing.md
      notebooks:
        - all steps: notebooks/collect_all_steps.md
  - About: about.md

# Markdown Extensions for better formatting
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: "#"
