[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "press"  
version = "0.1.0"       
description = "A package for analyzing CRS data"  
license = { text = "MIT" } 
dependencies = [
    "pandas",
    "numpy==1.26.4",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocstrings-python",
    "requests",
    "pyarrow",
    "matplotlib",
    "langdetect",
    "fasttext-wheel",
    "spacy",
    "nltk",
    "rapidfuzz",
    "swifter",
    "openpyxl",
    "torch",
    "transformers",
    "scikit-learn",
    "datasets",
    "sentencepiece",
    "accelerate",
    "ray",
    "wordcloud"
]
readme = "README.md"  # Optional, path to your README file
requires-python = ">=3.7"  # Specify the minimum Python version

